from problems.utils import log


@log
def main():
    """
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
    find the sum of the even-valued terms.
    """
    s = 0
    f0, f1 = 1, 2
    while f1 < 4e6:
        if f1 % 2 == 0:
            s += f1
        f0, f1 = f1, f0 + f1
    return s


if __name__ == '__main__':
    main()
